name: Deploy Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/fleek
  schedule:
    - cron: "* */1 * * *" # every one hour

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.117.0
    permissions:
      contents: write
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
      - name: Build
        run: |
          npm ci
          make website
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_BASE_URL: ${{ steps.pages.outputs.base_url }}
      - name: Upload Data Aggregates
        # Used for local debugging
        if: (failure() || success())
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./artifacts
      - name: Configure git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com>"
          git config --global user.name "${GITHUB_ACTOR}"
      - name: Push
        run: |
          git add -f ./www/public
          git commit -m "chore: update public site"
          git push -f origin HEAD:fleek-deploy