name: Release
on:
  push:
    paths: [CHANGELOG.md]
    branches: [main, release]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main, release]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: pl-strflt/changelog-driven-release@v1
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' }}
      - if: github.event_name == 'pull_request' && steps.release.outputs.tag != ''
        uses: marocchino/sticky-pull-request-comment@3d60a5b2dae89d44e0c6ddc69dd7536aec2071cd # v2.5.0
        with:
          header: release
          recreate: true
          message: |
            ## [${{ steps.release.outputs.tag }}](${{ steps.release.outputs.url }})

            ${{ steps.release.outputs.body }}
      - if: github.event_name != 'pull_request' && steps.release.outputs.tag != ''
        env:
          RELEASE: |
            {
              "tag": "${{ steps.release.outputs.tag }}",
              "tags": "${{ steps.release.outputs.tags }}",
              "body": "${{ steps.release.outputs.body }}",
              "url": "${{ steps.release.outputs.url }}",
              "draft": false
            }
        run: jq -n "$RELEASE" > release.json
      - if: github.event_name != 'pull_request' && steps.release.outputs.tag != ''
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.json
