name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    steps:
      - uses: ipfs/download-ipfs-distribution-action@v1
      - uses: ipfs/start-ipfs-daemon-action@v1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - uses: actions/checkout@v3
        with:
          path: 'gateway-conformance'
      - name: Extract fixtures
        uses: ./gateway-conformance/.github/actions/extract-fixtures
        with:
          output: fixtures
      - name: Provision Kubo Gateway
        run: find ./fixtures -name '*.car' -exec ipfs dag import {} \;
      - name: Run the tests
        uses: ./gateway-conformance/.github/actions/test
        with:
          gateway-url: http://127.0.0.1:8080
          xml: output.xml
          html: output.html
          markdown: report.md
      - name: Set summary
        uses: dorny/test-reporter@v1
        with:
          path: output.xml
          reporter: java-junit
      - name: Upload one-page HTML report
        if: (failure() || success())
        uses: actions/upload-artifact@v3
        with:
          name: conformance.html
          path: ./output.html
