name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: ipfs/download-ipfs-distribution-action@v1
      - uses: ipfs/start-ipfs-daemon-action@v1
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run patch
      - run: npm run prepare
      - run: npm run provision kubo
      - run: npm test
